### ISSUE TITLE
使用qq邮箱给搭建的临时邮箱发送邮件，收不到邮件

### ISSUE THREAD

**Issue by zhenzi0322** [rev1si0n/another-tmp-mailbox#4]
为什么会出现收不到邮件的呢？qq邮箱中一直的发送状态一直显示：正在投递

**Comment by rev1si0n** [comment]
看看是不是域名解析没配置好，下面有说配置的内容，然后检查是不是25端口没开(是否可以连接)

**Comment by zhenzi0322** [comment]
> 看看是不是域名解析没配置好，下面有说配置的内容，然后检查是不是25端口没开(是否可以连接)

开了的。刚才机器中有一个/usr/libexec/postfix 占用了，然后我把这个占用的kill掉了

**Comment by zhenzi0322** [comment]
> 看看是不是域名解析没配置好，下面有说配置的内容，然后检查是不是25端口没开(是否可以连接)


```

Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1062, in create_server
    sock.bind(sa)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 281, in <module>
    smtp.start()
  File "/home/Envs/temp-mail/lib/python3.6/site-packages/aiosmtpd/controller.py", line 210, in start
    raise self._thread_exception
  File "/home/Envs/temp-mail/lib/python3.6/site-packages/aiosmtpd/controller.py", line 176, in _run
    srv: AsyncServer = self.loop.run_until_complete(self.server_coro)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1066, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 25): address already in use
```

**Comment by rev1si0n** [comment]
> > 看看是不是域名解析没配置好，下面有说配置的内容，然后检查是不是25端口没开(是否可以连接)
> 
> 
> 
> 开了的。刚才机器中有一个/usr/libexec/postfix 占用了，然后我把这个占用的kill掉了

你直接kill应该不行，先看看这个有没有用处，没用就停掉服务，具体怎么停看你什么系统了。

**Comment by zhenzi0322** [comment]
> > > 看看是不是域名解析没配置好，下面有说配置的内容，然后检查是不是25端口没开(是否可以连接)
> > 
> > 
> > 开了的。刚才机器中有一个/usr/libexec/postfix 占用了，然后我把这个占用的kill掉了
> 
> 你直接kill应该不行，先看看这个有没有用处，没用就停掉服务，具体怎么停看你什么系统了。

centos7.9

**Comment by zhenzi0322** [comment]
> > > 看看是不是域名解析没配置好，下面有说配置的内容，然后检查是不是25端口没开(是否可以连接)
> > 
> > 
> > 开了的。刚才机器中有一个/usr/libexec/postfix 占用了，然后我把这个占用的kill掉了
> 
> 你直接kill应该不行，先看看这个有没有用处，没用就停掉服务，具体怎么停看你什么系统了。

我不停止postfix，就启动不了main.py
